In [1]:
import pandas as pd

In [2]:
zomato = pd.read_csv('zomato.csv')
zomato

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [3]:
zomato.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'restaurant name', 'restaurant type',
       'rate (out of 5)', 'num of ratings', 'avg cost (two people)',
       'online_order', 'table booking', 'cuisines type', 'area',
       'local address'],
      dtype='object')

In [4]:
zomato.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB

In [7]:
zomato['restaurant type'].unique()

array(['Quick Bites', 'Cafe', 'Casual Dining', 'Takeaway, Delivery',
       'Bar, Casual Dining', 'Fine Dining', 'Pub', 'Casual Dining, Bar',
       'Delivery', 'Kiosk', 'Food Court', 'Microbrewery', 'Bar', 'Mess',
       'Bakery', 'Dessert Parlor', 'Beverage Shop', 'Sweet Shop', 'Dhaba',
       'Cafe, Quick Bites', 'Microbrewery, Casual Dining',
       'Dessert Parlor, Beverage Shop', 'Bar, Lounge',
       'Quick Bites, Mess', 'Food Truck', 'Lounge, Bar',
       'Cafe, Dessert Parlor', 'Quick Bites, Beverage Shop',
       'Pub, Casual Dining', 'Pub, Microbrewery',
       'Sweet Shop, Quick Bites', 'Cafe, Bakery', 'Fine Dining, Bar',
       'Bar, Pub', 'Bakery, Quick Bites', 'Bakery, Beverage Shop',
       'Bakery, Dessert Parlor', 'Takeaway', 'Lounge',
       'Microbrewery, Lounge', 'Lounge, Microbrewery',
       'Casual Dining, Microbrewery', 'Casual Dining, Pub',
       'Bakery, Cafe', 'Casual Dining, Cafe', 'Microbrewery, Pub',
       'Cafe, Bar', 'Quick Bites, Cafe', 'Cafe, Casual Dining',
       'Pub, Bar', 'Quick Bites, Dessert Parlor',
       'Dessert Parlor, Quick Bites', 'Beverage Shop, Quick Bites',
       'Food Court, Quick Bites', 'Quick Bites, Sweet Shop',
       'Casual Dining, Lounge', 'Dessert Parlor, Bakery',
       'Dessert Parlor, Sweet Shop', 'Beverage Shop, Dessert Parlor',
       'Cafe, Lounge', 'Casual Dining, Quick Bites', 'Club',
       'Food Court, Casual Dining', 'Quick Bites, Bakery',
       'Lounge, Casual Dining', 'Food Court, Dessert Parlor',
       'Dessert Parlor, Cafe', 'Lounge, Cafe',
       'Dessert Parlor, Food Court', 'Microbrewery, Bar', 'Confectionery',
       'Fine Dining, Lounge', 'Casual Dining, Irani Cafee',
       'Fine Dining, Microbrewery', 'Beverage Shop, Cafe', 'Bhojanalya',
       'Food Court, Beverage Shop', 'Quick Bites, Food Court',
       'Casual Dining, Sweet Shop', 'Quick Bites, Meat Shop',
       'Club, Casual Dining'], dtype=object)

In [8]:
zomato['restaurant type'] = zomato['restaurant type'].str.split(', ')
zomato['restaurant type']

0              [Quick Bites]
1              [Quick Bites]
2                     [Cafe]
3            [Casual Dining]
4            [Casual Dining]
                ...
7100                  [Cafe]
7101        [Dessert Parlor]
7102    [Takeaway, Delivery]
7103         [Casual Dining]
7104            [Food Truck]
Name: restaurant type, Length: 7105, dtype: object

In [10]:
zomato_exploded = zomato.explode('restaurant type')
zomato_exploded

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,Takeaway,3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7102,7102,7102,Zu's Doner Kebaps,Delivery,3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [13]:
zomato_exploded['restaurant type'].unique()

array(['Quick Bites', 'Cafe', 'Casual Dining', 'Takeaway', 'Delivery',
       'Bar', 'Fine Dining', 'Pub', 'Kiosk', 'Food Court', 'Microbrewery',
       'Mess', 'Bakery', 'Dessert Parlor', 'Beverage Shop', 'Sweet Shop',
       'Dhaba', 'Lounge', 'Food Truck', 'Club', 'Confectionery',
       'Irani Cafee', 'Bhojanalya', 'Meat Shop'], dtype=object)

In [18]:
zomato_exploded['cuisines type'] = zomato_exploded['cuisines type'].str.split(', ')
zomato_exploded['cuisines type']

0                                             [Fast Food]
1                                  [Fast Food, Beverages]
2                                       [Cafe, Beverages]
3                             [Biryani, Mughlai, Chinese]
4       [BBQ, Continental, North Indian, Chinese, Beve...
                              ...
7100                 [Cafe, Italian, Continental, Burger]
7101                                           [Desserts]
7102               [Turkish, Fast Food, Biryani, Chinese]
7103                     [North Indian, Mughlai, Chinese]
7104                                          [Fast Food]
Name: cuisines type, Length: 7105, dtype: object

In [24]:
zomato_exploded2 = zomato_exploded.explode('cuisines type')
zomato_exploded3 = zomato_exploded2.explode('restaurant type')
zomato_exploded3

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Fast Food,"Byresandra,Tavarekere,Madiwala",HSR
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Beverages,"Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Cafe,Bannerghatta Road,Bannerghatta Road
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Beverages,Bannerghatta Road,Bannerghatta Road
...,...,...,...,...,...,...,...,...,...,...,...,...
7102,7102,7102,Zu's Doner Kebaps,Delivery,3.7,33,350.0,No,No,Chinese,Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,North Indian,Kammanahalli,HBR Layout
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Mughlai,Kammanahalli,HBR Layout
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Chinese,Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [20]:
zomato_exploded2['cuisines type'].unique()

array(['Fast Food', 'Beverages', 'Cafe', 'Biryani', 'Mughlai', 'Chinese',
       'BBQ', 'Continental', 'North Indian', 'Italian', 'Arabian',
       'Sandwich', 'Rolls', 'Burger', 'Kebab', 'Asian', 'European',
       'Pizza', 'Salad', 'Street Food', 'Japanese', 'Thai', 'Malaysian',
       'Vietnamese', 'Korean', 'South Indian', 'Kerala', 'Seafood',
       'American', 'Steak', 'Bakery', 'Tibetan', 'Nepalese', 'Momos',
       'Mediterranean', 'Finger Food', 'Ice Cream', 'Middle Eastern',
       'Bar Food', 'Mithai', 'Andhra', 'Desserts', 'Healthy Food',
       'French', 'Hyderabadi', 'Bengali', 'Oriya', 'Chettinad',
       'Lebanese', 'Mangalorean', 'Afghan', 'Modern Indian', 'Juices',
       'Awadhi', 'Mexican', 'Sushi', 'Burmese', 'Indonesian', 'Assamese',
       'Iranian', 'Charcoal Chicken', 'Kashmiri', 'Singaporean',
       'Spanish', 'Hot dogs', 'Tamil', 'Coffee', 'Tea', 'Maharashtrian',
       'North Eastern', 'Bihari', 'Rajasthani', 'Lucknowi', 'Gujarati',
       'Bubble Tea', 'Bohri', 'Turkish', 'Tex-Mex', 'Wraps', 'German',
       'Drinks Only', 'Konkan', 'Goan', 'South American', 'Roast Chicken',
       'Naga', 'Jewish', 'Vegan', 'Greek', 'African', 'Grill', 'Afghani',
       'Parsi', 'Mongolian', 'Portuguese', 'Australian', 'Paan',
       'British', 'Sindhi', 'Indian', 'Sri Lankan', 'Pan Asian',
       'Russian', 'Raw Meats', 'Belgian', 'Cantonese'], dtype=object)

In [25]:
median_rate = zomato_exploded3['rate (out of 5)'].median()
median_rate

np.float64(3.6)

In [26]:
zomato_exploded3['rate (out of 5)'] = zomato_exploded3['rate (out of 5)'].fillna(median_rate)
zomato_exploded3.isna().sum()

Unnamed: 0.1               0
Unnamed: 0                 0
restaurant name            0
restaurant type            0
rate (out of 5)            0
num of ratings             0
avg cost (two people)    156
online_order               0
table booking              0
cuisines type              0
area                       0
local address              0
dtype: int64

In [28]:
mean_of_avg_cost = zomato_exploded3['avg cost (two people)'].mean().round(1)
mean_of_avg_cost

np.float64(624.5)

In [29]:
zomato_exploded3['avg cost (two people)'] = zomato_exploded3['avg cost (two people)'].fillna(mean_of_avg_cost)
zomato_exploded3.isna().sum()

Unnamed: 0.1             0
Unnamed: 0               0
restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
dtype: int64

In [31]:
min_rate = zomato_exploded3['rate (out of 5)'].min()
max_rate = zomato_exploded3['rate (out of 5)'].max()

In [32]:
min_rate

np.float64(1.8)

In [33]:
max_rate

np.float64(4.9)

In [47]:
def group_rate (rate):
    if rate < 3:
        return "LOW RATING"
    if rate < 3.6:
        return "AWERAGE RATING"
    if rate < 4.3:
        return "GOOD RATING"
    else: 
        return "EXCELENT RATING"
        
zomato_exploded3['RATING GROUPS'] = zomato_exploded3['rate (out of 5)'].apply(group_rate)

In [38]:
zomato_exploded3

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address,RATING GROUPS
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur,AWERAGE RATING
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Fast Food,"Byresandra,Tavarekere,Madiwala",HSR,GOOD RATING
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Beverages,"Byresandra,Tavarekere,Madiwala",HSR,GOOD RATING
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Cafe,Bannerghatta Road,Bannerghatta Road,GOOD RATING
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Beverages,Bannerghatta Road,Bannerghatta Road,GOOD RATING
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7102,7102,7102,Zu's Doner Kebaps,Delivery,3.7,33,350.0,No,No,Chinese,Malleshwaram,RT Nagar,GOOD RATING
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,North Indian,Kammanahalli,HBR Layout,GOOD RATING
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Mughlai,Kammanahalli,HBR Layout,GOOD RATING
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Chinese,Kammanahalli,HBR Layout,GOOD RATING
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore,AWERAGE RATING

In [39]:
min_cost = zomato_exploded3['avg cost (two people)'].min()
max_cost = zomato_exploded3['avg cost (two people)'].max()

In [40]:
min_cost

np.float64(40.0)

In [41]:
max_cost

np.float64(6000.0)

In [42]:
median_cost = zomato_exploded3['avg cost (two people)'].median()
median_cost

np.float64(500.0)

In [43]:
def cost_group (cost):
    if cost < 250:
        return "VERY CHEAP"
    if cost < 500:
        return "CHEAP"
    if cost < 1000:
        return "MODERATE"
    if cost < 2500:
        return "EXPENSIVE"
    if cost < 4000:
        return "LUXURY"
    else:
        return "ULTRA LUXARY"

zomato_exploded3['AVERAGE_COST_GROUPS'] = zomato_exploded3['avg cost (two people)'].apply(cost_group)
zomato_exploded3

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address,RATING GROUPS,AVERAGE_COST_GROUPS
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur,AWERAGE RATING,VERY CHEAP
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Fast Food,"Byresandra,Tavarekere,Madiwala",HSR,GOOD RATING,CHEAP
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Beverages,"Byresandra,Tavarekere,Madiwala",HSR,GOOD RATING,CHEAP
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Cafe,Bannerghatta Road,Bannerghatta Road,GOOD RATING,CHEAP
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Beverages,Bannerghatta Road,Bannerghatta Road,GOOD RATING,CHEAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7102,7102,7102,Zu's Doner Kebaps,Delivery,3.7,33,350.0,No,No,Chinese,Malleshwaram,RT Nagar,GOOD RATING,CHEAP
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,North Indian,Kammanahalli,HBR Layout,GOOD RATING,MODERATE
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Mughlai,Kammanahalli,HBR Layout,GOOD RATING,MODERATE
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Chinese,Kammanahalli,HBR Layout,GOOD RATING,MODERATE
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore,AWERAGE RATING,VERY CHEAP

In [49]:
zomato_exploded3.to_csv('zomoto_clean_groups.csv', index = False)

In [45]:
zomato_exploded3

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address,RATING GROUPS,AVERAGE_COST_GROUPS
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur,AWERAGE RATING,VERY CHEAP
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Fast Food,"Byresandra,Tavarekere,Madiwala",HSR,GOOD RATING,CHEAP
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,Beverages,"Byresandra,Tavarekere,Madiwala",HSR,GOOD RATING,CHEAP
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Cafe,Bannerghatta Road,Bannerghatta Road,GOOD RATING,CHEAP
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,Beverages,Bannerghatta Road,Bannerghatta Road,GOOD RATING,CHEAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7102,7102,7102,Zu's Doner Kebaps,Delivery,3.7,33,350.0,No,No,Chinese,Malleshwaram,RT Nagar,GOOD RATING,CHEAP
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,North Indian,Kammanahalli,HBR Layout,GOOD RATING,MODERATE
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Mughlai,Kammanahalli,HBR Layout,GOOD RATING,MODERATE
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,Chinese,Kammanahalli,HBR Layout,GOOD RATING,MODERATE
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore,AWERAGE RATING,VERY CHEAP

In [48]:
zomato_exploded3.isna().sum()

Unnamed: 0.1             0
Unnamed: 0               0
restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
RATING GROUPS            0
AVERAGE_COST_GROUPS      0
dtype: int64