In [4]:
import pandas as pd

In [5]:
retailSTORES = pd.read_csv('retail_store_sales.csv')
retailSTORES.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [6]:
retailSTORES.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
retailSTORES[['ItemPrefix', 'NumberOFitem', 'ShortItemName']] = retailSTORES['Item'].str.split('_', expand=True)
retailSTORES

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10,PAT
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17,MILK
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12,BUT
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16,BEV
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6,FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23,PAT
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2,BEV
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7,BUT
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7,FUR
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9,FOOD

In [31]:
# Funkcija koja popunjava NaN u ShortItemName najčešćom vrednošću unutar svake kategorije
def fill_short_item_name_with_mode(group):
    mode_value = group['ShortItemName'].mode()
    if not mode_value.empty:
        group['ShortItemName'] = group['ShortItemName'].fillna(mode_value[0])
    return group

# Primeni funkciju po grupama 'Category'
retailSTORES = retailSTORES.groupby('Category').apply(fill_short_item_name_with_mode)
retailSTORES

C:\Users\Bane\AppData\Local\Temp\ipykernel_20336\1412834056.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  retailSTORES = retailSTORES.groupby('Category').apply(fill_short_item_name_with_mode)

                 Transaction ID Customer ID    Category         Item  \
Category
Beverages  3        TXN_9458126     CUST_06   Beverages  Item_16_BEV
           15       TXN_1809665     CUST_14   Beverages          NaN
           20       TXN_9939063     CUST_14   Beverages   Item_7_BEV
           35       TXN_6398436     CUST_15   Beverages  Item_25_BEV
           38       TXN_8312797     CUST_14   Beverages  Item_11_BEV
...                         ...         ...         ...          ...
Patisserie 12520    TXN_7459774     CUST_20  Patisserie  Item_23_PAT
           12536    TXN_2919179     CUST_23  Patisserie   Item_1_PAT
           12563    TXN_5394856     CUST_08  Patisserie  Item_17_PAT
           12569    TXN_2318174     CUST_18  Patisserie   Item_1_PAT
           12570    TXN_9347481     CUST_18  Patisserie  Item_23_PAT

                  Price Per Unit  Quantity  Total Spent  Payment Method  \
Category
Beverages  3                27.5       9.0        247.5     Credit Card
           15               24.5       NaN          NaN     Credit Card
           20               14.0       9.0        126.0  Digital Wallet
           35               41.0       7.0        287.0     Credit Card
           38               20.0       5.0        100.0  Digital Wallet
...                          ...       ...          ...             ...
Patisserie 12520            38.0       4.0        152.0     Credit Card
           12536             5.0       7.0         35.0  Digital Wallet
           12563            29.0       2.0         58.0  Digital Wallet
           12569             5.0       9.0         45.0  Digital Wallet
           12570            38.0       4.0        152.0     Credit Card

                  Location Transaction Date Discount Applied ItemPrefix  \
Category
Beverages  3        Online       2022-05-07              NaN       Item
           15     In-store       2022-05-11              NaN        NaN
           20     In-store       2024-01-14              NaN       Item
           35     In-store       2024-06-03             True       Item
           38       Online       2022-06-03              NaN       Item
...                    ...              ...              ...        ...
Patisserie 12520    Online       2022-04-25             True       Item
           12536    Online       2022-11-22             True       Item
           12563    Online       2024-10-24             True       Item
           12569  In-store       2024-05-13            False       Item
           12570  In-store       2023-09-03              NaN       Item

                 NumberOFitem ShortItemName
Category
Beverages  3               16           BEV
           15             NaN           BEV
           20               7           BEV
           35              25           BEV
           38              11           BEV
...                       ...           ...
Patisserie 12520           23           PAT
           12536            1           PAT
           12563           17           PAT
           12569            1           PAT
           12570           23           PAT

[12575 rows x 14 columns]

In [9]:
retailSTORES['ShortItemName'].isna().sum()

np.int64(1213)

In [10]:
retailSTORES.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
ItemPrefix          1213
NumberOFitem        1213
ShortItemName       1213
dtype: int64

In [13]:
# Pronađi najčešću vrednost ShortItemName po Category
mode_per_category = retailSTORES.groupby('Category')['ShortItemName'].agg(lambda x: x.mode().iloc[0])

# Mapiraj najčešću vrednost nazad na originalni DataFrame i postavi kolonu ShortItemName
retailSTORES['ShortItemName'] = retailSTORES['Category'].map(mode_per_category)

retailSTORES

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10,PAT
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17,MILK
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12,BUT
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16,BEV
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6,FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23,PAT
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2,BEV
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7,BUT
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7,FUR
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9,FOOD

In [14]:
retailSTORES.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
ItemPrefix          1213
NumberOFitem        1213
ShortItemName          0
dtype: int64

In [ ]:
def fill_missing_numbers(group):
    max_val = group['NumberOFitem'].max(skipna=True)
    if pd.isna(max_val):
        max_val = 0
    missing_indices = group[group['NumberOFitem'].isna()].index
    for i, idx in enumerate(missing_indices, 1):
        group.at[idx, 'NumberOFitem'] = max_val + i
    return group

df_filled = df.groupby('Category').apply(fill_missing_numbers).reset_index(drop=True)

In [16]:
distinct_values = retailSTORES['Category'].unique()
distinct_values

array(['Patisserie', 'Milk Products', 'Butchers', 'Beverages', 'Food',
       'Furniture', 'Electric household essentials',
       'Computers and electric accessories'], dtype=object)

In [19]:
import numpy as np

# Ako još nije konvertovano u brojeve:
retailSTORES['NumberOFitem'] = pd.to_numeric(retailSTORES['NumberOFitem'], errors='coerce')

# Lista kategorija koje želiš da obradiš
categories = [
    'Patisserie', 'Milk Products', 'Butchers', 'Beverages', 'Food',
    'Furniture', 'Electric household essentials',
    'Computers and electric accessories'
]

# Popunjavanje praznih vrednosti po kategorijama
for cat in categories:
    if cat in retailSTORES['Category'].unique():
        mask = retailSTORES['Category'] == cat
        max_val = retailSTORES.loc[mask, 'NumberOFitem'].max(skipna=True)
        if pd.isna(max_val):
            max_val = 0
        missing_indices = retailSTORES[mask & retailSTORES['NumberOFitem'].isna()].index
        for i, idx in enumerate(missing_indices, 1):
            retailSTORES.at[idx, 'NumberOFitem'] = max_val + i


retailSTORES

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10.0,PAT
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17.0,MILK
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12.0,BUT
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16.0,BEV
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6.0,FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23.0,PAT
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2.0,BEV
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7.0,BUT
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7.0,FUR
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9.0,FOOD

In [21]:
distinct_values2 = retailSTORES.loc[retailSTORES['Category'] == 'Milk Products', 'NumberOFitem'].unique()
distinct_values2

array([ 17.,  26.,  16.,  27.,  28.,  19.,   6.,   8.,   4.,  23.,  21.,
         1.,  24.,   3.,  11.,  15.,   2.,  29.,  30.,   9.,  13.,  22.,
        31.,  18.,  32.,  14.,  33.,  34.,  20.,  35.,   5.,   7.,  36.,
        25.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,
        47.,  48.,  49.,  50.,  12.,  51.,  52.,  53.,  10.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 151., 152., 153., 154.,
       155., 156., 157., 158., 159., 160., 161., 162., 163., 164., 165.,
       166., 167., 168., 169., 170., 171., 172., 173., 174., 175., 176.,
       177., 178., 179., 180., 181., 182., 183., 184.])

In [24]:
retailSTORES['ItemPrefix'] = retailSTORES['ItemPrefix'].fillna("Item")
retailSTORES

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10.0,PAT
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17.0,MILK
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12.0,BUT
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16.0,BEV
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6.0,FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23.0,PAT
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2.0,BEV
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7.0,BUT
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7.0,FUR
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9.0,FOOD

In [25]:
retailSTORES.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
ItemPrefix             0
NumberOFitem           0
ShortItemName          0
dtype: int64

In [26]:
retailSTORES = retailSTORES.drop(columns=['Item'])
retailSTORES

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName
0,TXN_6867343,CUST_09,Patisserie,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10.0,PAT
1,TXN_3731986,CUST_22,Milk Products,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17.0,MILK
2,TXN_9303719,CUST_02,Butchers,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12.0,BUT
3,TXN_9458126,CUST_06,Beverages,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16.0,BEV
4,TXN_4575373,CUST_05,Food,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6.0,FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23.0,PAT
12571,TXN_4009414,CUST_03,Beverages,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2.0,BEV
12572,TXN_5306010,CUST_11,Butchers,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7.0,BUT
12573,TXN_5167298,CUST_04,Furniture,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7.0,FUR
12574,TXN_2407494,CUST_23,Food,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9.0,FOOD

In [27]:
retailSTORES['NumberOFitem'] = retailSTORES['NumberOFitem'].astype(int)
retailSTORES

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName
0,TXN_6867343,CUST_09,Patisserie,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10,PAT
1,TXN_3731986,CUST_22,Milk Products,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17,MILK
2,TXN_9303719,CUST_02,Butchers,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12,BUT
3,TXN_9458126,CUST_06,Beverages,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16,BEV
4,TXN_4575373,CUST_05,Food,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6,FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23,PAT
12571,TXN_4009414,CUST_03,Beverages,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2,BEV
12572,TXN_5306010,CUST_11,Butchers,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7,BUT
12573,TXN_5167298,CUST_04,Furniture,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7,FUR
12574,TXN_2407494,CUST_23,Food,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9,FOOD

In [29]:
retailSTORES['ITEM'] = retailSTORES['ItemPrefix'].astype(str) + "_" + retailSTORES['NumberOFitem'].astype(str) + "_" + retailSTORES['ShortItemName'].astype(str)
retailSTORES

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName,ITEM
0,TXN_6867343,CUST_09,Patisserie,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10,PAT,Item_10_PAT
1,TXN_3731986,CUST_22,Milk Products,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17,MILK,Item_17_MILK
2,TXN_9303719,CUST_02,Butchers,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12,BUT,Item_12_BUT
3,TXN_9458126,CUST_06,Beverages,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16,BEV,Item_16_BEV
4,TXN_4575373,CUST_05,Food,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6,FOOD,Item_6_FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23,PAT,Item_23_PAT
12571,TXN_4009414,CUST_03,Beverages,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2,BEV,Item_2_BEV
12572,TXN_5306010,CUST_11,Butchers,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7,BUT,Item_7_BUT
12573,TXN_5167298,CUST_04,Furniture,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7,FUR,Item_7_FUR
12574,TXN_2407494,CUST_23,Food,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9,FOOD,Item_9_FOOD

In [30]:
def fill_empty_price(row):
    if pd.isna(row['Price Per Unit']):
        if row['Quantity'] != 0 and not pd.isna(row['Quantity']):
            return row['Total Spent'] / row['Quantity']
        else:
            return 0  # ili neka druga vrednost po želji ako Quantity nije validan
    else:
        return row['Price Per Unit']

retailSTORES['Price Per Unit'] = retailSTORES.apply(fill_empty_price, axis=1)

In [31]:
retailSTORES

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName,ITEM
0,TXN_6867343,CUST_09,Patisserie,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10,PAT,Item_10_PAT
1,TXN_3731986,CUST_22,Milk Products,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17,MILK,Item_17_MILK
2,TXN_9303719,CUST_02,Butchers,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12,BUT,Item_12_BUT
3,TXN_9458126,CUST_06,Beverages,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16,BEV,Item_16_BEV
4,TXN_4575373,CUST_05,Food,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6,FOOD,Item_6_FOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23,PAT,Item_23_PAT
12571,TXN_4009414,CUST_03,Beverages,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2,BEV,Item_2_BEV
12572,TXN_5306010,CUST_11,Butchers,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7,BUT,Item_7_BUT
12573,TXN_5167298,CUST_04,Furniture,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7,FUR,Item_7_FUR
12574,TXN_2407494,CUST_23,Food,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9,FOOD,Item_9_FOOD

In [32]:
retailSTORES.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
ItemPrefix             0
NumberOFitem           0
ShortItemName          0
ITEM                   0
dtype: int64

In [33]:
retailSTORES.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Price Per Unit    12575 non-null  float64
 4   Quantity          11971 non-null  float64
 5   Total Spent       11971 non-null  float64
 6   Payment Method    12575 non-null  object
 7   Location          12575 non-null  object
 8   Transaction Date  12575 non-null  object
 9   Discount Applied  8376 non-null   object
 10  ItemPrefix        12575 non-null  object
 11  NumberOFitem      12575 non-null  int64
 12  ShortItemName     12575 non-null  object
 13  ITEM              12575 non-null  object
dtypes: float64(3), int64(1), object(10)
memory usage: 1.3+ MB

In [35]:
retailSTORES = retailSTORES.dropna(subset=['Quantity'])
retailSTORES.isna().sum()

Transaction ID         0
Customer ID            0
Category               0
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    3988
ItemPrefix             0
NumberOFitem           0
ShortItemName          0
ITEM                   0
dtype: int64

In [37]:
retailSTORES['Transaction Date'] = pd.to_datetime(retailSTORES['Transaction Date'], errors='coerce')
retailSTORES['Month'] = retailSTORES['Transaction Date'].dt.month
retailSTORES['Year'] = retailSTORES['Transaction Date'].dt.year
retailSTORES

C:\Users\Bane\AppData\Local\Temp\ipykernel_20512\2781947237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retailSTORES['Transaction Date'] = pd.to_datetime(retailSTORES['Transaction Date'], errors='coerce')
C:\Users\Bane\AppData\Local\Temp\ipykernel_20512\2781947237.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retailSTORES['Month'] = retailSTORES['Transaction Date'].dt.month
C:\Users\Bane\AppData\Local\Temp\ipykernel_20512\2781947237.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retailSTORES['Year'] = retailSTORES['Transaction Date'].dt.year

,Transaction ID,Customer ID,Category,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,ItemPrefix,NumberOFitem,ShortItemName,ITEM,Month,Year
0,TXN_6867343,CUST_09,Patisserie,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,Item,10,PAT,Item_10_PAT,4,2024
1,TXN_3731986,CUST_22,Milk Products,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,Item,17,MILK,Item_17_MILK,7,2023
2,TXN_9303719,CUST_02,Butchers,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,Item,12,BUT,Item_12_BUT,10,2022
3,TXN_9458126,CUST_06,Beverages,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,Item,16,BEV,Item_16_BEV,5,2022
4,TXN_4575373,CUST_05,Food,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,Item,6,FOOD,Item_6_FOOD,10,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,Item,23,PAT,Item_23_PAT,9,2023
12571,TXN_4009414,CUST_03,Beverages,6.5,9.0,58.5,Cash,Online,2022-08-12,False,Item,2,BEV,Item_2_BEV,8,2022
12572,TXN_5306010,CUST_11,Butchers,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,Item,7,BUT,Item_7_BUT,8,2024
12573,TXN_5167298,CUST_04,Furniture,14.0,6.0,84.0,Cash,Online,2023-12-30,True,Item,7,FUR,Item_7_FUR,12,2023
12574,TXN_2407494,CUST_23,Food,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,Item,9,FOOD,Item_9_FOOD,8,2022

In [42]:
Pivot_Category = retailSTORES.pivot_table(
    index=['Category', 'Year', 'Month'],    
    values=['Quantity', 'Total Spent', 'Price Per Unit','Customer ID'],
    aggfunc={
        'Quantity': 'sum',
        'Total Spent': 'sum',
        'Price Per Unit': 'mean',
        'Customer ID': 'count'
    }
)
Pivot_Category

                       Customer ID  Price Per Unit  Quantity  Total Spent
Category   Year Month
Beverages  2022 1               39       26.923077     222.0       5784.0
                2               41       23.512195     272.0       6457.0
                3               39       22.038462     205.0       4493.0
                4               34       23.308824     179.0       4096.0
                5               37       25.229730     229.0       5643.5
...                            ...             ...       ...          ...
Patisserie 2024 9               42       21.964286     214.0       4749.5
                10              46       25.347826     241.0       5969.0
                11              36       22.791667     219.0       5004.0
                12              48       23.125000     276.0       6469.5
           2025 1               20       20.600000      87.0       1732.5

[296 rows x 4 columns]

In [44]:
Pivot_Payment_Method = retailSTORES.pivot_table(
    index=['Payment Method', 'Year', 'Month'],    
    values=['Quantity', 'Total Spent', 'Price Per Unit', 'Customer ID'],
    aggfunc={
        'Quantity': 'sum',
        'Total Spent': 'sum',
        'Price Per Unit': 'mean',
        'Customer ID': 'count'
    }
)

Pivot_Payment_Method

                           Customer ID  Price Per Unit  Quantity  Total Spent
Payment Method Year Month
Cash           2022 1              128       25.050781     796.0      19568.0
                    2               98       24.591837     538.0      13325.0
                    3              115       22.308696     685.0      15317.0
                    4              113       21.380531     550.0      11684.0
                    5              115       24.265217     616.0      14895.5
...                                ...             ...       ...          ...
Digital Wallet 2024 9              105       25.000000     522.0      13110.0
                    10              99       25.318182     581.0      14713.0
                    11             115       24.486957     638.0      15472.0
                    12             116       21.383621     727.0      16112.0
               2025 1               76       23.809211     409.0       9611.0

[111 rows x 4 columns]

In [45]:
Pivot_Location = retailSTORES.pivot_table(
    index=['Location', 'Year', 'Month'],    
    values=['Quantity', 'Total Spent', 'Price Per Unit', 'Customer ID'],
    aggfunc={
        'Quantity': 'sum',
        'Total Spent': 'sum',
        'Price Per Unit': 'mean',
        'Customer ID': 'count'
    }
)

Pivot_Location

                     Customer ID  Price Per Unit  Quantity  Total Spent
Location Year Month
In-store 2022 1              178       24.963483    1016.0      25294.0
              2              152       24.026316     871.0      21581.0
              3              161       23.493789     887.0      20998.0
              4              166       21.743976     861.0      18703.5
              5              138       23.695652     741.0      17683.5
...                          ...             ...       ...          ...
Online   2024 9              170       24.367647     890.0      22073.5
              10             164       24.060976     887.0      20722.0
              11             194       24.221649    1057.0      25598.0
              12             175       21.380000    1037.0      22336.0
         2025 1               92       23.750000     527.0      12130.0

[74 rows x 4 columns]

In [46]:
with pd.ExcelWriter('RETAIL_python_pivots.xlsx', engine = 'openpyxl') as writer:
    Pivot_Category.to_excel(writer, sheet_name='Pivot_Category')
    Pivot_Payment_Method.to_excel(writer, sheet_name='Pivot_Payment_Method')
    Pivot_Location.to_excel(writer, sheet_name=' Pivot_Location')