In [13]:
import pandas as pd

In [21]:
superstore = pd.read_csv('Sample - Superstore.csv', encoding='ISO-8859-1')
superstore.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
row_id_index =superstore.set_index('Row ID')
row_id_index.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [15]:
superstore.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [16]:
superstore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [7]:
superstore.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [23]:
superstore['Order Date'] = pd.to_datetime(superstore['Order Date'])
superstore['Ship Date'] = pd.to_datetime(superstore['Ship Date'])

superstore['Between OrdAndShip days'] = (superstore['Ship Date'] - superstore['Order Date']).dt.days

superstore[['Order Date', 'Ship Date', 'Between OrdAndShip days']].head()

  Order Date  Ship Date  Between OrdAndShip days
0 2016-11-08 2016-11-11                        3
1 2016-11-08 2016-11-11                        3
2 2016-06-12 2016-06-16                        4
3 2015-10-11 2015-10-18                        7
4 2015-10-11 2015-10-18                        7

In [18]:
superstore.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Between OrdAndShip days'],
      dtype='object')

In [19]:
superstore.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,Between OrdAndShip days
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,3.958175
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,3.000000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,4.000000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,5.000000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,7.000000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.747567

In [11]:
superstore_year_month = superstore.groupby([
    superstore['Order Date'].dt.year,
    superstore['Order Date'].dt.month
]).agg({
    'Between OrdAndShip days': 'mean',
    'Quantity': 'sum',
    'Sales': 'sum',
    'Profit': 'sum'
})

superstore_year_month

                       Between OrdAndShip days  Quantity        Sales  \
Order Date Order Date
2014       1                          4.164557       284   14236.8950
           2                          4.173913       159    4519.8920
           3                          3.974522       585   55691.0090
           4                          4.051852       536   28295.3450
           5                          3.803279       466   23648.2870
           6                          4.177778       521   34595.1276
           7                          3.839161       550   33946.3930
           8                          4.045752       609   27909.4685
           9                          4.059701      1000   81777.3508
           10                         3.358491       573   31453.3930
           11                         4.261006      1219   78628.7167
           12                         3.960432      1079   69545.6205
2015       1                          4.741379       236   18174.0756
           2                          4.109375       239   11951.4110
           3                          3.702899       515   38726.2520
           4                          4.337500       543   34195.2085
           5                          4.034247       575   30131.6865
           6                          4.152174       486   24797.2920
           7                          3.721429       557   28765.3250
           8                          3.955975       598   36898.3322
           9                          4.290102      1086   64595.9180
           10                         3.590361       631   31404.9235
           11                         3.978395      1310   75972.5635
           12                         3.924051      1203   74919.5212
2016       1                          4.101124       358   18542.4910
           2                          3.518072       306   22978.8150
           3                          3.509202       579   51715.8750
           4                          4.458824       635   38750.0390
           5                          3.880000       863   56987.7280
           6                          3.417085       742   40344.5340
           7                          3.815920       758   39261.9630
           8                          4.329545       693   31115.3743
           9                          4.005510      1316   73410.0249
           10                         4.188776       767   59687.7450
           11                         3.937838      1406   79411.9658
           12                         4.031250      1414   96999.0430
2017       1                          4.109677       597   43971.3740
           2                          4.373832       363   20301.1334
           3                          3.567227       885   58872.3528
           4                          3.817734       733   36521.5361
           5                          3.731405       887   44261.1102
           6                          4.061224       931   52981.7257
           7                          4.150442       840   45264.4160
           8                          4.036697       884   63120.8880
           9                          3.688453      1660   87866.6520
           10                         3.969799      1133   77776.9232
           11                         3.806100      1840  118447.8250
           12                         4.041126      1723   83829.3188

                           Profit
Order Date Order Date
2014       1            2450.1907
           2             862.3084
           3             498.7299
           4            3488.8352
           5            2738.7096
           6            4976.5244
           7            -841.4826
           8            5318.1050
           9            8328.0994
           10           3448.2573
           11           9292.1269
           12           8983.5699
2015       1           -3281.0070
           2            2813.8508
           3            9732.0978
           4            4187.4962
           5            4667.8690
           6            3335.5572
           7            3288.6483
           8            5355.8084
           9            8209.1627
           10           2817.3660
           11          12474.7884
           12           8016.9659
2016       1            2824.8233
           2            5004.5795
           3            3611.9680
           4            2977.8149
           5            8662.1464
           6            4750.3781
           7            4432.8779
           8            2062.0693
           9            9328.6576
           10          16243.1425
           11           4011.4075
           12          17885.3093
2017       1            7140.4391
           2            1613.8720
           3           14751.8915
           4             933.2900
           5            6342.5828
           6            8223.3357
           7            6952.6212
           8            9040.9557
           9           10991.5556
           10           9275.2755
           11           9690.1037
           12           8483.3468

In [20]:
superstore_ship_mode_year_month = superstore.groupby([
    superstore['Ship Mode'],
    superstore['Order Date'].dt.year,
    superstore['Order Date'].dt.month
]).agg({
    'Between OrdAndShip days': 'mean',
    'Quantity': 'sum',
    'Sales': 'sum',
    'Profit': 'sum'
})

superstore_ship_mode_year_month

                                      Between OrdAndShip days  Quantity  \
Ship Mode      Order Date Order Date
First Class    2014       1                          1.727273        44
                          2                          2.571429        25
                          3                          1.941176        61
                          4                          1.916667        37
                          5                          2.263158        84
...                                                       ...       ...
Standard Class 2017       8                          5.375000       481
                          9                          4.907950       868
                          10                         5.183333       692
                          11                         4.979592       960
                          12                         5.021429      1078

                                           Sales      Profit
Ship Mode      Order Date Order Date
First Class    2014       1            1056.5300   -218.7960
                          2             843.9160    315.8389
                          3            2219.0900    440.8799
                          4            3138.6160    407.3710
                          5            3415.6910    213.3243
...                                          ...         ...
Standard Class 2017       8           34483.7920   5974.0232
                          9           46291.0660   7340.4364
                          10          40483.6032   2270.8677
                          11          64153.4810  11251.6900
                          12          50400.1828   2899.9221

[188 rows x 4 columns]

In [24]:
superstore_geography_year_month = superstore.groupby([
    superstore['Country'],
    superstore['City'],
    superstore['State'],
    superstore['Order Date'].dt.year,
    superstore['Order Date'].dt.month
]).agg({
    'Between OrdAndShip days': 'mean',
    'Quantity': 'sum',
    'Sales': 'sum',
    'Profit': 'sum'
})

superstore_geography_year_month

                                                           Between OrdAndShip days  \
Country       City     State        Order Date Order Date
United States Aberdeen South Dakota 2017       11                              3.0
              Abilene  Texas        2017       12                              2.0
              Akron    Ohio         2014       5                               2.0
                                               11                              6.0
                                    2015       2                               5.0
...                                                                            ...
              Yucaipa  California   2015       8                               7.0
              Yuma     Arizona      2016       5                               0.0
                                               7                               1.0
                                               9                               2.0
                                    2017       10                              5.0

                                                           Quantity    Sales  \
Country       City     State        Order Date Order Date
United States Aberdeen South Dakota 2017       11                 3   25.500
              Abilene  Texas        2017       12                 2    1.392
              Akron    Ohio         2014       5                  7  165.168
                                               11                 3    5.742
                                    2015       2                 13  427.548
...                                                             ...      ...
              Yucaipa  California   2015       8                  5   50.800
              Yuma     Arizona      2016       5                  7  185.528
                                               7                  6   44.856
                                               9                  4   10.496
                                    2017       10                 5  599.985

                                                             Profit
Country       City     State        Order Date Order Date
United States Aberdeen South Dakota 2017       11            6.6300
              Abilene  Texas        2017       12           -3.7584
              Akron    Ohio         2014       5             9.5076
                                               11           -4.5936
                                    2015       2           -92.8368
...                                                             ...
              Yucaipa  California   2015       8            13.2080
              Yuma     Arizona      2016       5            48.7011
                                               7           -35.8848
                                               9             1.1808
                                    2017       10         -479.9880

[2960 rows x 4 columns]

In [25]:
superstore_segment_year_month = superstore.groupby([
    superstore['Segment'],
    superstore['Order Date'].dt.year,
    superstore['Order Date'].dt.month
]).agg({
    'Between OrdAndShip days': 'mean',
    'Quantity': 'sum',
    'Sales': 'sum',
    'Profit': 'sum'
})

superstore_segment_year_month

                                   Between OrdAndShip days  Quantity  \
Segment     Order Date Order Date
Consumer    2014       1                          4.428571       180
                       2                          4.370370        95
                       3                          3.935897       296
                       4                          3.854167       184
                       5                          4.169014       237
...                                                    ...       ...
Home Office 2017       8                          5.030303       139
                       9                          3.259259       279
                       10                         3.625000       277
                       11                         3.520408       376
                       12                         4.033898       215

                                       Sales     Profit
Segment     Order Date Order Date
Consumer    2014       1            6927.817   766.2263
                       2            3167.854   496.8669
                       3           11869.304   597.2773
                       4            9108.612  1155.0757
                       5           12819.163   698.9171
...                                      ...        ...
Home Office 2017       8            5813.300  1222.6869
                       9           19904.346  2199.2031
                       10          29705.515  4001.2531
                       11          24013.684  2861.2104
                       12          13072.431  3407.7021

[144 rows x 4 columns]

In [26]:
superstore_product_category_year_month = superstore.groupby([
    superstore['Category'],
    superstore['Sub-Category'],
    superstore['Order Date'].dt.year,
    superstore['Order Date'].dt.month
]).agg({
    'Between OrdAndShip days': 'mean',
    'Quantity': 'sum',
    'Sales': 'sum',
    'Profit': 'sum'
})

superstore_product_category_year_month

                                               Between OrdAndShip days  \
Category   Sub-Category Order Date Order Date
Furniture  Bookcases    2014       1                          2.400000
                                   3                          4.333333
                                   4                          5.000000
                                   5                          4.000000
                                   6                          5.000000
...                                                                ...
Technology Phones       2017       8                          4.411765
                                   9                          3.694444
                                   10                         4.333333
                                   11                         3.477273
                                   12                         4.181818

                                               Quantity       Sales     Profit
Category   Sub-Category Order Date Order Date
Furniture  Bookcases    2014       1                 16   1010.0550  -326.7848
                                   3                 17   1706.4460  -141.2250
                                   4                  3    308.4990   -18.1470
                                   5                  9    640.6310  -189.6215
                                   6                  9    759.5736    -6.5766
...                                                 ...         ...        ...
Technology Phones       2017       8                 75  10037.5680  1341.2843
                                   9                120  15318.8360  1448.4239
                                   10               112   8749.6380  1261.3973
                                   11               175  17407.1400  2562.6603
                                   12               112   9067.0560  1680.8431

[782 rows x 4 columns]

In [28]:
superstore_product_name_year_month = superstore.groupby([
    superstore['Product Name'],
    superstore['Order Date'].dt.year,
    superstore['Order Date'].dt.month
]).agg({
    'Between OrdAndShip days': 'mean',
    'Quantity': 'sum',
    'Sales': 'sum',
    'Profit': 'sum'
})

superstore_product_name_year_month

                                                                          Between OrdAndShip days  \
Product Name                                       Order Date Order Date
"While you Were Out" Message Book, One Form per... 2017       9                               4.0
                                                              10                              6.0
                                                              11                              3.0
#10 Gummed Flap White Envelopes, 100/Box           2015       11                              7.0
                                                   2016       1                               6.0
...                                                                                           ...
netTALK DUO VoIP Telephone Service                 2014       12                              5.0
                                                   2015       6                               5.0
                                                              9                               3.0
                                                   2016       1                               6.0
                                                   2017       7                               4.0

                                                                          Quantity  \
Product Name                                       Order Date Order Date
"While you Were Out" Message Book, One Form per... 2017       9                  3
                                                              10                 2
                                                              11                 3
#10 Gummed Flap White Envelopes, 100/Box           2015       11                 2
                                                   2016       1                  4
...                                                                            ...
netTALK DUO VoIP Telephone Service                 2014       12                 4
                                                   2015       6                  3
                                                              9                  2
                                                   2016       1                  9
                                                   2017       7                  4

                                                                            Sales  \
Product Name                                       Order Date Order Date
"While you Were Out" Message Book, One Form per... 2017       9             8.904
                                                              10            7.420
                                                              11            8.904
#10 Gummed Flap White Envelopes, 100/Box           2015       11            6.608
                                                   2016       1            16.520
...                                                                           ...
netTALK DUO VoIP Telephone Service                 2014       12          167.968
                                                   2015       6           125.976
                                                              9           104.980
                                                   2016       1           377.928
                                                   2017       7           167.968

                                                                            Profit
Product Name                                       Order Date Order Date
"While you Were Out" Message Book, One Form per... 2017       9             3.3390
                                                              10            3.7100
                                                              11            3.3390
#10 Gummed Flap White Envelopes, 100/Box           2015       11            2.1476
                                                   2016       1             7.5992
...                                                                            ...
netTALK DUO VoIP Telephone Service                 2014       12           62.9880
                                                   2015       6            47.2410
                                                              9            52.4900
                                                   2016       1           141.7230
                                                   2017       7            62.9880

[9251 rows x 4 columns]

In [30]:
superstore_year_month.to_csv('superstore_year_month.csv',index=False)

In [31]:
superstore_ship_mode_year_month.to_csv('superstore_ship_mode_year_month.csv',index=False)

In [32]:
superstore_geography_year_month.to_csv('superstore_geography_year_month.csv',index=False)

In [33]:
superstore_segment_year_month.to_csv('superstore_segment_year_month.csv',index=False)

In [34]:
superstore_product_category_year_month.to_csv('superstore_product_category_year_month.csv',index=False)

In [35]:
superstore_product_name_year_month.to_csv('superstore_product_name_year_month.csv',index=False)