In [1]:
import pandas as pd

In [3]:
bookshop = pd.read_csv('blackwell_shop_raw.csv')
bookshop.head()

,isbn,publication_date,type,category,link_book_page,name,subtitle,edition,author,gbpprice,...,language,no_of_pages,height,width,spine,weight,salesRank,short_blurb,long_blurb,blurbReview
0,9780241508695,01 Sep 2022,Hardback,artanddesign,/bookshop/product/Apollo-Remastered-by-Andy-Sa...,Apollo Remastered,NaN,NaN,Andy Saunders,49.99,...,English,456,302.0,318.0,37.0,3222,3.0,In a frozen vault in Houston sits the original...,<p><b>AN INSTANT <i>SUNDAY TIMES </i>BESTSELLE...,<b>Andy Saunders&#39; remastered images are so...
1,9780753558256,21 Jul 2022,Hardback,artanddesign,/bookshop/product/Femina-by-Janina-Ramirez/978...,Femina,"A New History of the Middle Ages, Through the ...",NaN,Janina Ramirez,15.45,...,English,"xv, 447",163.0,241.0,43.0,696,180.0,BBC historian Janina Ramirez has uncovered cou...,"<p><font size=""+1""><br><b><u>THE INSTANT <i>SU...",Revelatory... Ramirez shows again and again th...
2,9781849947879,01 Sep 2022,Hardback,artanddesign,/bookshop/product/Wild-Textiles-by-Alice-Fox/9...,Wild Textiles,"Grown, Foraged, Found",NaN,Alice Fox,15.67,...,English,128,224.0,283.0,18.0,38,35.0,"Harness the world of nature in textile art, fr...",A guide to harnessing the world of nature to c...,NaN
3,9781472223845,30 Aug 2022,Hardback,artanddesign,/bookshop/product/The-Marriage-Portrait-by-Mag...,The Marriage Portrait,NaN,Hardback original,Maggie O'Farrell,16.99,...,English,438,164.0,243.0,44.0,850,38.0,"Winter, 1561. Lucrezia, Duchess of Ferrara, is...",<p><b>'Every bit as evocative and spellbinding...,<b>Every bit as evocative and spellbinding as ...
4,9781855147430,06 Feb 2022,Hardback,artanddesign,/bookshop/product/Elizabeth-II-by-National-Por...,Elizabeth II,"Princess, Queen, Icon",NaN,National Portrait Gallery (Great Britain) (cre...,14.95,...,English,152,178.0,226.0,21.0,618,151.0,With just under a thousand portraits of Queen ...,With just under a thousand portraits of Queen ...,NaN

In [4]:
bookshop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11623 entries, 0 to 11622
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   isbn               11623 non-null  int64
 1   publication_date   11619 non-null  object
 2   type               11620 non-null  object
 3   category           11623 non-null  object
 4   link_book_page     11623 non-null  object
 5   name               11623 non-null  object
 6   subtitle           5505 non-null   object
 7   edition            4683 non-null   object
 8   author             11580 non-null  object
 9   gbpprice           11623 non-null  float64
 10  discount           11610 non-null  float64
 11  isSecondHand       11623 non-null  bool
 12  publisher          11621 non-null  object
 13  published_country  11363 non-null  object
 14  imprint            11617 non-null  object
 15  language           11549 non-null  object
 16  no_of_pages        11060 non-null  object
 17  height             11609 non-null  float64
 18  width              11607 non-null  float64
 19  spine              11488 non-null  float64
 20  weight             11623 non-null  int64
 21  salesRank          6794 non-null   float64
 22  short_blurb        11281 non-null  object
 23  long_blurb         11142 non-null  object
 24  blurbReview        5046 non-null   object
dtypes: bool(1), float64(6), int64(2), object(16)
memory usage: 2.1+ MB

In [7]:
bookshop.columns = bookshop.columns.str.strip()
bookshop['publication_date'] = pd.to_datetime(bookshop['publication_date'], errors='coerce')

In [9]:
bookshop['type'].isna().sum()

np.int64(3)

In [10]:
bookshop['type']=bookshop['type'].fillna("UNKNOWN")
bookshop['type'].isna().sum()

np.int64(0)

In [11]:
bookshop['subtitle']=bookshop['subtitle'].fillna("WITHOUT SUBTITLE")
bookshop['subtitle'].isna().sum()

np.int64(0)

In [12]:
bookshop['edition']=bookshop['edition'].fillna("NOT DEFINED")
bookshop['edition'].isna().sum()

np.int64(0)

In [14]:
bookshop['author']=bookshop['author'].fillna("UNKNOWN")
bookshop['author'].isna().sum()

np.int64(0)

In [15]:
bookshop['discount']=bookshop['discount'].fillna(0)
bookshop['discount'].isna().sum()

np.int64(0)

In [16]:
bookshop['publisher']=bookshop['publisher'].fillna("UNKNOWN")
bookshop['publisher'].isna().sum()

np.int64(0)

In [17]:
bookshop['published_country']=bookshop['published_country'].fillna("UNKNOWN")
bookshop['published_country'].isna().sum()

np.int64(0)

In [18]:
bookshop['imprint']=bookshop['imprint'].fillna("UNKNOWN")
bookshop['imprint'].isna().sum()

np.int64(0)

In [19]:
bookshop['language']=bookshop['language'].fillna("UNKNOWN")
bookshop['language'].isna().sum()

np.int64(0)

In [24]:
# Uklanjanje svega osim cifara (0–9) ### CHAT GPT
bookshop['no_of_pages'] = bookshop['no_of_pages'].astype(str).str.replace(r'\D+', '', regex=True)
bookshop['no_of_pages'] = pd.to_numeric(bookshop['no_of_pages'], errors='coerce')

In [25]:
mean_no_of_pages = bookshop['no_of_pages'].mean()
bookshop['no_of_pages']=bookshop['no_of_pages'].fillna(mean_no_of_pages)
bookshop['no_of_pages'].isna().sum()

np.int64(0)

In [26]:
bookshop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11623 entries, 0 to 11622
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   isbn               11623 non-null  int64
 1   publication_date   11462 non-null  datetime64[ns]
 2   type               11623 non-null  object
 3   category           11623 non-null  object
 4   link_book_page     11623 non-null  object
 5   name               11623 non-null  object
 6   subtitle           11623 non-null  object
 7   edition            11623 non-null  object
 8   author             11623 non-null  object
 9   gbpprice           11623 non-null  float64
 10  discount           11623 non-null  float64
 11  isSecondHand       11623 non-null  bool
 12  publisher          11623 non-null  object
 13  published_country  11623 non-null  object
 14  imprint            11623 non-null  object
 15  language           11623 non-null  object
 16  no_of_pages        11623 non-null  float64
 17  height             11609 non-null  float64
 18  width              11607 non-null  float64
 19  spine              11488 non-null  float64
 20  weight             11623 non-null  int64
 21  salesRank          6794 non-null   float64
 22  short_blurb        11281 non-null  object
 23  long_blurb         11142 non-null  object
 24  blurbReview        5046 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(7), int64(2), object(14)
memory usage: 2.1+ MB

In [27]:
median_height = bookshop['height'].median()
bookshop['height']=bookshop['height'].fillna(mean_no_of_pages)
bookshop['height'].isna().sum()

np.int64(0)

In [28]:
median_height = bookshop['width'].median()
bookshop['width']=bookshop['width'].fillna(mean_no_of_pages)
bookshop['width'].isna().sum()

np.int64(0)

In [29]:
bookshop['spine']=bookshop['spine'].fillna("UNKNOWN")
bookshop['spine'].isna().sum()

np.int64(0)

In [30]:
median_weight = bookshop['weight'].median()
bookshop['weight']=bookshop['weight'].fillna(mean_no_of_pages)
bookshop['weight'].isna().sum()

np.int64(0)

In [31]:
bookshop.head()

,isbn,publication_date,type,category,link_book_page,name,subtitle,edition,author,gbpprice,...,language,no_of_pages,height,width,spine,weight,salesRank,short_blurb,long_blurb,blurbReview
0,9780241508695,2022-09-01,Hardback,artanddesign,/bookshop/product/Apollo-Remastered-by-Andy-Sa...,Apollo Remastered,WITHOUT SUBTITLE,NOT DEFINED,Andy Saunders,49.99,...,English,4560.0,302.0,318.0,37.0,3222,3.0,In a frozen vault in Houston sits the original...,<p><b>AN INSTANT <i>SUNDAY TIMES </i>BESTSELLE...,<b>Andy Saunders&#39; remastered images are so...
1,9780753558256,2022-07-21,Hardback,artanddesign,/bookshop/product/Femina-by-Janina-Ramirez/978...,Femina,"A New History of the Middle Ages, Through the ...",NOT DEFINED,Janina Ramirez,15.45,...,English,4470.0,163.0,241.0,43.0,696,180.0,BBC historian Janina Ramirez has uncovered cou...,"<p><font size=""+1""><br><b><u>THE INSTANT <i>SU...",Revelatory... Ramirez shows again and again th...
2,9781849947879,2022-09-01,Hardback,artanddesign,/bookshop/product/Wild-Textiles-by-Alice-Fox/9...,Wild Textiles,"Grown, Foraged, Found",NOT DEFINED,Alice Fox,15.67,...,English,1280.0,224.0,283.0,18.0,38,35.0,"Harness the world of nature in textile art, fr...",A guide to harnessing the world of nature to c...,NaN
3,9781472223845,2022-08-30,Hardback,artanddesign,/bookshop/product/The-Marriage-Portrait-by-Mag...,The Marriage Portrait,WITHOUT SUBTITLE,Hardback original,Maggie O'Farrell,16.99,...,English,4380.0,164.0,243.0,44.0,850,38.0,"Winter, 1561. Lucrezia, Duchess of Ferrara, is...",<p><b>'Every bit as evocative and spellbinding...,<b>Every bit as evocative and spellbinding as ...
4,9781855147430,2022-02-06,Hardback,artanddesign,/bookshop/product/Elizabeth-II-by-National-Por...,Elizabeth II,"Princess, Queen, Icon",NOT DEFINED,National Portrait Gallery (Great Britain) (cre...,14.95,...,English,1520.0,178.0,226.0,21.0,618,151.0,With just under a thousand portraits of Queen ...,With just under a thousand portraits of Queen ...,NaN

In [32]:
bookshop.to_csv('bookshoop_python_cleaned.csv',index=False)